"""add_is_active_to_traces

Revision ID: 58aff3490f93
Revises: c4148cbf9881
Create Date: 2026-01-10 18:22:57.776134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58aff3490f93'
down_revision = 'c4148cbf9881'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traces', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traces', 'is_active')
    # ### end Alembic commands ###
