"""add_guest_users_table

Revision ID: c4148cbf9881
Revises: 9699e24ec699
Create Date: 2026-01-09 11:10:31.436705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4148cbf9881'
down_revision = '9699e24ec699'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False, comment='Client-generated UUID for guest identification'),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True, comment='SHA-256 hash of browser characteristics'),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='User metadata: IP, user_agent, referrer, etc.'),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='First time this guest user was seen'),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last activity timestamp'),
    sa.Column('session_count', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Number of sessions created by this guest'),
    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether this guest is blocked from access'),
    sa.Column('blocked_reason', sa.Text(), nullable=True, comment='Reason for blocking (abuse, rate limit, etc.)'),
    sa.Column('data_retention_days', sa.Integer(), server_default=sa.text('90'), nullable=False, comment='Days before auto-deletion (GDPR compliance)'),
    sa.Column('consent_given', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether user gave consent for data tracking'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_users_client_id'), 'guest_users', ['client_id'], unique=True)
    op.create_index(op.f('ix_guest_users_device_fingerprint'), 'guest_users', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_guest_users_last_seen_at'), 'guest_users', ['last_seen_at'], unique=False)
    op.drop_index(op.f('idx_agents_slug'), table_name='agents')
    op.drop_constraint(op.f('uq_agents_slug'), 'agents', type_='unique')
    op.create_index(op.f('ix_agents_slug'), 'agents', ['slug'], unique=True)
    op.add_column('sessions', sa.Column('guest_user_id', sa.UUID(), nullable=True, comment='Guest user who created this session'))
    op.alter_column('sessions', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_sessions_last_active'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_user_id'), table_name='sessions')
    op.create_index(op.f('ix_sessions_guest_user_id'), 'sessions', ['guest_user_id'], unique=False)
    op.create_index(op.f('ix_sessions_last_active_at'), 'sessions', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'guest_users', ['guest_user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('trace_steps', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('trace_steps', 'tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('trace_steps', 'cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=False,
               existing_server_default=sa.text('0.000000'))
    op.alter_column('trace_steps', 'is_error',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('trace_steps', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trace_steps', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_steps_order'), table_name='trace_steps')
    op.drop_index(op.f('idx_steps_trace_id'), table_name='trace_steps')
    op.drop_index(op.f('idx_steps_type'), table_name='trace_steps')
    op.create_index(op.f('ix_trace_steps_step_type'), 'trace_steps', ['step_type'], unique=False)
    op.create_index(op.f('ix_trace_steps_trace_id'), 'trace_steps', ['trace_id'], unique=False)
    op.alter_column('traces', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_cost',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=False,
               existing_server_default=sa.text('0.000000'))
    op.alter_column('traces', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'is_successful',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('traces', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('traces', 'environment',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'production'::character varying"))
    op.alter_column('traces', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_traces_agent_id'), table_name='traces')
    op.drop_index(op.f('idx_traces_created_at'), table_name='traces')
    op.drop_index(op.f('idx_traces_env'), table_name='traces')
    op.drop_index(op.f('idx_traces_session_id'), table_name='traces')
    op.create_index(op.f('ix_traces_agent_id'), 'traces', ['agent_id'], unique=False)
    op.create_index(op.f('ix_traces_environment'), 'traces', ['environment'], unique=False)
    op.create_index(op.f('ix_traces_session_id'), 'traces', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traces_session_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_environment'), table_name='traces')
    op.drop_index(op.f('ix_traces_agent_id'), table_name='traces')
    op.create_index(op.f('idx_traces_session_id'), 'traces', ['session_id'], unique=False)
    op.create_index(op.f('idx_traces_env'), 'traces', ['environment'], unique=False)
    op.create_index(op.f('idx_traces_created_at'), 'traces', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_traces_agent_id'), 'traces', ['agent_id'], unique=False)
    op.alter_column('traces', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('traces', 'environment',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'production'::character varying"))
    op.alter_column('traces', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('traces', 'is_successful',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('traces', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_cost',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=True,
               existing_server_default=sa.text('0.000000'))
    op.alter_column('traces', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_trace_steps_trace_id'), table_name='trace_steps')
    op.drop_index(op.f('ix_trace_steps_step_type'), table_name='trace_steps')
    op.create_index(op.f('idx_steps_type'), 'trace_steps', ['step_type'], unique=False)
    op.create_index(op.f('idx_steps_trace_id'), 'trace_steps', ['trace_id'], unique=False)
    op.create_index(op.f('idx_steps_order'), 'trace_steps', ['trace_id', 'sequence_order'], unique=False)
    op.alter_column('trace_steps', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('trace_steps', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trace_steps', 'is_error',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('trace_steps', 'cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=True,
               existing_server_default=sa.text('0.000000'))
    op.alter_column('trace_steps', 'tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('trace_steps', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_last_active_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_guest_user_id'), table_name='sessions')
    op.create_index(op.f('idx_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_last_active'), 'sessions', [sa.literal_column('last_active_at DESC')], unique=False)
    op.alter_column('sessions', 'last_active_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('sessions', 'guest_user_id')
    op.drop_index(op.f('ix_agents_slug'), table_name='agents')
    op.create_unique_constraint(op.f('uq_agents_slug'), 'agents', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_agents_slug'), 'agents', ['slug'], unique=False)
    op.drop_index(op.f('ix_guest_users_last_seen_at'), table_name='guest_users')
    op.drop_index(op.f('ix_guest_users_device_fingerprint'), table_name='guest_users')
    op.drop_index(op.f('ix_guest_users_client_id'), table_name='guest_users')
    op.drop_table('guest_users')
    # ### end Alembic commands ###
